# --- Release tarball in a per-deployment private bucket --------------------

resource "aws_s3_bucket" "artifacts" {
  bucket        = "${local.prefix}-${data.aws_caller_identity.current.account_id}"
  force_destroy = true
  tags          = { Name = "${local.prefix}-${data.aws_caller_identity.current.account_id}" }
}

resource "aws_s3_bucket_public_access_block" "artifacts" {
  bucket                  = aws_s3_bucket.artifacts.id
  block_public_acls       = true
  block_public_policy     = true
  ignore_public_acls      = true
  restrict_public_buckets = true
}

resource "aws_s3_bucket_ownership_controls" "artifacts" {
  bucket = aws_s3_bucket.artifacts.id
  rule {
    object_ownership = "BucketOwnerEnforced"
  }
}

resource "aws_s3_bucket_server_side_encryption_configuration" "artifacts" {
  bucket = aws_s3_bucket.artifacts.id
  rule {
    apply_server_side_encryption_by_default {
      sse_algorithm = "AES256"
    }
  }
}

resource "aws_s3_bucket_versioning" "artifacts" {
  bucket = aws_s3_bucket.artifacts.id
  versioning_configuration {
    status = "Disabled"
  }
}

locals {
  # Tolerate a missing tarball so `down.sh` can still destroy after bin/ was
  # cleaned; creating/updating the object is guarded by the precondition below.
  binary_exists = fileexists(var.binary_path)
  binary_key    = "releases/${basename(var.binary_path)}"
  binary_sha256 = local.binary_exists ? filesha256(var.binary_path) : "missing"
}

resource "aws_s3_object" "binary" {
  bucket       = aws_s3_bucket.artifacts.id
  key          = local.binary_key
  source       = var.binary_path
  source_hash  = local.binary_exists ? filemd5(var.binary_path) : null
  content_type = "application/gzip"

  lifecycle {
    precondition {
      condition     = local.binary_exists
      error_message = "binary_path does not exist: ${var.binary_path}"
    }
  }

  depends_on = [aws_s3_bucket_public_access_block.artifacts]
}

# --- Secrets generated by Terraform ----------------------------------------
# The instance key and master key live in Terraform (not on the VM) so a
# replaced VM (new release, domain added) keeps decrypting the RDS data and
# existing links keep their key. Both are base64url (no padding) of 32 random
# bytes, the format the copper-cloud config expects.

resource "random_bytes" "instance_key" {
  length = 32
}

resource "random_bytes" "master_key" {
  length = 32
}

locals {
  instance_key = replace(replace(trimsuffix(random_bytes.instance_key.base64, "="), "+", "-"), "/", "_")
  master_key   = replace(replace(trimsuffix(random_bytes.master_key.base64, "="), "+", "-"), "/", "_")
  ssm_prefix   = "/copper-cloud/${var.name}"
}

# Secrets reach the VM through SSM SecureString (fetched by cloud-init with the
# instance role) so they never appear in EC2 user data or the console log.
resource "aws_ssm_parameter" "database_url" {
  name        = "${local.ssm_prefix}/database-url"
  description = "copper-cloud ${var.name}: DATABASE_URL for the RDS instance"
  type        = "SecureString"
  value       = local.database_url
}

resource "aws_ssm_parameter" "instance_key" {
  name        = "${local.ssm_prefix}/instance-key"
  description = "copper-cloud ${var.name}: instance key (X-Copper-Instance)"
  type        = "SecureString"
  value       = local.instance_key
}

resource "aws_ssm_parameter" "master_key" {
  name        = "${local.ssm_prefix}/master-key"
  description = "copper-cloud ${var.name}: master key wrapping per-user data keys"
  type        = "SecureString"
  value       = local.master_key
}

# Initial password of the portal admin (created by install.sh on first boot). Changing it
# in the portal does not update this parameter; install.sh never resets an existing admin.
resource "random_password" "admin" {
  length  = 24
  special = false
}

resource "aws_ssm_parameter" "admin_password" {
  name        = "${local.ssm_prefix}/admin-password"
  description = "copper-cloud ${var.name}: initial admin portal password (${local.admin_email_label})"
  type        = "SecureString"
  value       = random_password.admin.result
}

# Written by the VM. Terraform creates them (so destroy removes them) and
# resets them to "pending" whenever the VM is replaced, so up.sh never reads a
# stale "ready" from a previous VM.
resource "terraform_data" "boot" {
  # Anything that replaces the VM must also reset the status parameters.
  triggers_replace = [sha256(local.user_data), local.subnet_id]
}

resource "aws_ssm_parameter" "status" {
  name        = "${local.ssm_prefix}/status"
  description = "copper-cloud ${var.name}: install status written by cloud-init (pending|installing|ready|failed: <step>)"
  type        = "String"
  value       = "pending"

  lifecycle {
    ignore_changes       = [value]
    replace_triggered_by = [terraform_data.boot]
  }
}

resource "aws_ssm_parameter" "link_code" {
  name        = "${local.ssm_prefix}/link-code"
  description = "copper-cloud ${var.name}: link code written by cloud-init"
  type        = "SecureString"
  value       = "pending"

  lifecycle {
    ignore_changes       = [value]
    replace_triggered_by = [terraform_data.boot]
  }
}
